### ISSUE TITLE
English signature is default, even on non-english language settings

### ISSUE THREAD

**Issue by Norbert80** [deltachat/deltachat-android#1502]
Hi there,

on my Samsung phone with German language environment Delta Chat uses English signature ("Sent with my...") as default for new profiles.

(GUI is German as expected.)
 
Found with 10.10.5 build. But I think I experienced the same bug already with 10.8.1 build.

**Comment by gerryfrancis** [comment]
@Norbert80 Thank you for your report. When you send a message to a person with a classic mailer, does the mail contain a German or the English signature? Maybe it is just shown wrong in the preferences dialog.

**Comment by Hocuri** [comment]
I could not reproduce this.

@Norbert80 Did you maybe change your system language from English to German recently? In this case, you might want to "force stop" Delta Chat once.

**Comment by angelo-fuchs** [comment]
I could reproduce this (1.10.5).
Using existing DC installation.
Switching Language to "System" (which is German in my case)
Switch Account and create a new one.
UI is in German but the signature that arrived at my test mail account was "Sent with my Delta Chat Messenger: https://delta.chat"

As @Hocuri could not reproduce it, this probably needs more digging.

**Comment by angelo-fuchs** [comment]
On another account I manually set the Language to "German" fix and the problem remains.

**Comment by gerryfrancis** [comment]
> Switching Language to "System" (which is German in my case)
> Switch Account and create a new one.

The signature of the newly created account is English, this seems to be default. A function to instantly switch the signature to the language currently active must be developed.

**Comment by angelo-fuchs** [comment]
This applies to other languages as well, just tried with Esperanto where the problem appears as well.

**Comment by Norbert80** [comment]
> @Norbert80 Thank you for your report. When you send a message to a person with a classic mailer, does the mail contain a German or the English signature? Maybe it is just shown wrong in the preferences dialog.

English.

**Comment by Norbert80** [comment]
> I could not reproduce this on 1.10.4
> 
> @Norbert80 Did you maybe change your system language from English to German recently?

No. Never.

**Comment by Norbert80** [comment]
There are more English strings popping up in my German GUI:

![grafik](https://user-images.githubusercontent.com/6921696/88588227-7f9dc680-d057-11ea-8f54-b7e34bb58f9e.png)
![grafik](https://user-images.githubusercontent.com/6921696/88588255-89bfc500-d057-11ea-825c-9992aec999d9.png)
![grafik](https://user-images.githubusercontent.com/6921696/88588299-9b08d180-d057-11ea-9f57-d7d95decab3c.png)

**Comment by Norbert80** [comment]
Hi there,

I found out something interesting.

I always thought that I never have experienced this language bug *before* I have used Delta Chat from F-Droid.

To check this I just tried the recent Play Store build.
Result: I get the German signature string beside the German GUI.

So it looks like this bug only affects F-droid builds.

Has anyone an idea why?

**Comment by r10s** [comment]
there was some recent change in picking the language, https://github.com/deltachat/deltachat-android/pull/1391/files, maybe that's related somehow.

**Comment by angelo-fuchs** [comment]
Just tested with GPlay 1.10.4: Issue remains. UI is in German, Mail elements (Subject and Signature) are in English.
Language is German (manually), System language is German as well.

**Comment by angelo-fuchs** [comment]
After restart the signature became German, the "Message from" segment of the subject remained English.

**Comment by gerryfrancis** [comment]
@angelo-fuchs Confirmed. I will try to update to 1.10.5 later on and see if it helps.

**Comment by angelo-fuchs** [comment]
@gerryfrancis It doesn't, I can reproduce on current master.

**Comment by angelo-fuchs** [comment]
During Debugging I added a breakpoint in ApplicationDcContext:136 (setStockTranslations)
All its calls were returning the German text, so I'm uncertain where the English text is given to the core atm.

If one restarts the phone OR opens the settings / Appearance even once the value is set properly.

**Comment by angelo-fuchs** [comment]
found it. It is in stock.rs:56

The issue also appears if one just switches from one account to another (already existing) one.
It seems that the core does not yet know of the internationalized strings in this scenario.

**Comment by Norbert80** [comment]
> found it. It is in stock.rs:56
> 
> The issue also appears if one just switches from one account to another (already existing) one.
> It seems that the core does not yet know of the internationalized strings in this scenario.

@angelo-fuchs Thanks you very much for this finding. It matches with my experience. (I use multi-account with the F-Droid build but checked only single-account with Google Play build.)

So it looks like the problem started for me as I begun to use multi-profile feature.

**Comment by angelo-fuchs** [comment]
@Norbert80 The fix merged, so the bug should be gone with the next version.
Thanks for reporting!

**Comment by Norbert80** [comment]
@angelo-fuchs Thank you very much! I will check and confirm as soon as the new build becomes available on F-Droid.

Btw... does anyone know why Delta Chat releases are delayed that much on F-Droid? Are these delays caused by F-Droid?

**Comment by angelo-fuchs** [comment]
@Norbert80 When we ship a new version it gets queued. So we have to wait until they come around to include it in their work.
Unfortunately we have no means to take any influence on when that's going to happen.

**Comment by Norbert80** [comment]
@angelo-fuchs Today I received the update via F-Droid.

- I can confirm that the signature has changed to German language now for all existing profiles. Thank you!

- I found one remaining translation issues on the message info box. If I select any message and press the i-button to display message info I still get English strings like "Sent:", "by", "State: Delivered", "Message-ID" and "Last seen as:"

**Comment by gerryfrancis** [comment]
@Norbert80 Although I can confirm this, I suggest to let this issue closed and to open a new one. Thanks!

**Comment by Norbert80** [comment]
Done. #1533
