### ISSUE TITLE
Time values in chat list not refreshed (as time passes by)

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-android#2029]
- Android version:
Android 11.

- Device:
Fairphone FP2 (Lineage OS 18.1 build RQ3A.210705.001 from 2021-08-06).

- Delta Chat version:
1.21.2 (latest nightly build).

- Expected behavior:
The time value of the latest sent/received message of each chat increases.

- Actual behavior:
The time value of the latest sent/received message of each chat does not increase. However, new messages are displayed instantly.

- Steps to reproduce the problem:
-- Open an existing chat and send a message.
-- Go back to the chat list (overview), and watch the time value for more than one minute. (Result: The value does not change.)

- Screenshots:
N/A.

- Logs:
N/A.

- Remarks:
-- The time values of the blobs within the chat are changed as expected.

**Comment by Gh0stz0x** [comment]
@gerryfrancis I try to see if it happens to me too. 🤔

**Comment by r10s** [comment]
a timer every minute and an update should fix that; i though, we already added sth. like that, but maybe that was ios or the message list ...

**Comment by r10s** [comment]
> @r10s should this go into the reliability project?

makes sense, i added it there.

**Comment by Hocuri** [comment]
> a timer every minute and an update should fix that; i though, we already added sth. like that

Yes, it's here:

https://github.com/deltachat/deltachat-android/blob/de734e941a9d1d54daf71b213259ee81ad227554/src/org/thoughtcrime/securesms/ConversationFragment.java#L129-L134

But probably there is a bug

**Comment by Hocuri** [comment]
Hmm, I just tried this out, but couldn't reproduce it for now (neither Fairphone 3, Android 10, nor emulated Pixel 2, Android 11).

**Comment by gerryfrancis** [comment]
@Hocuri The issue still exists, just stay at the chat overview for > 1 minute and you will see that the time values are not refreshed.

**Comment by Hocuri** [comment]
Just tried again, they are still refreshing... (I guess that they are refreshing after 1-2min, so waiting 1min may not be enough, maybe that's the problem?)

**Comment by rrthomas** [comment]
Doesn't refresh after hours for me. Android 9.

**Comment by Hocuri** [comment]
Weird...

**Comment by gerryfrancis** [comment]
> Doesn't refresh after hours for me. Android 9.

I am afraid I have to second that. Apparently, time values may be updated when a message is received, but not when the app does nothing.

@Hocuri Could background services have anything to do with it?

**Comment by AndreaLattmann** [comment]
@gerryfrancis there still this bug?

**Comment by gerryfrancis** [comment]
> @gerryfrancis there still this bug?

@AndreaLattmann Yes, unfortunately.

**Comment by r10s** [comment]
@adbenitez and me could not reproduce the bug on any of our testphones.

the only thing, we discovered, was that also _first_ update after resuming the chatlist also took 1 minute to happen; this is fixed by #2687 

i also double checked that the timer actually updates the list - and that the update is not done randomly by other things.

moreover, #2687 adds more logging - so, if the issue happens again, please open a fresh issue with a log and detailed device information 🙏

**Comment by gerryfrancis** [comment]
Looks like this issue is solved, many thanks to everyone involved! :)

**Comment by r10s** [comment]
puhhh, another 2yo issue closed more permantently :)

thanks for checking and confirming
