### ISSUE TITLE
Bad behavior by forwarding a message

### ISSUE THREAD

**Issue by webratte** [deltachat/deltachat-android#867]
- Platform (android/blackberry/anbox): Android 7.0
- Device: Huawei nova
- Delta Chat Version: 0.301.1
- Expected behavior: Message should only once forwarded. And then there should be the normal chat view.
If I like to forward this message again I should choose it again.

- Actual behavior: by pressing the back button twice it will offered to forward again

- Steps to reproduce the problem:
1. Long press a message
2. Press the forward button
3. Choose a chat  to forward this message
4. The message will forwarded after you pressed "ok" button in the pop up window
5. Press the back button
6. No pop up window (but normal chat view) is shown (also not if you tab a chat)
7. Press the back button again
8. Tap into a Chat
9. The pop up window pops up again.
10. This way you can forward this message again by accident.

**Comment by adbenitez** [comment]
I was keeping this issue in my "bug pocket" for a while, there was an issue also with the image not showing if you tried to forward an image to more than one people.

Anyway now in the 0.301.1 version I can't reproduce this any more, seems like it is fixed, now when I go back after forwarding a message I am in the chats list, not in the "Forward to..." view, so seems this issue was already solved.

**Comment by webratte** [comment]
Did you follow my instructions step by step? Especially step 5-9.


For me it's not fixed yet.

**Comment by adbenitez** [comment]
you are right I was going back only one time, 
but, while you will press back in the chat lists?? don't get me wrong, obviously this is not ok, but the only reason an user would press back in the chats list view is to leave the app, I don't see any real accident here :)

**Comment by webratte** [comment]
I forwarded already a message to the wrong receipient ;-)

Maybe I was a little bit hectic...

**Comment by adbenitez** [comment]
if something can go wrong... it will ;)

**Comment by Boehrsi** [comment]
The linked PR should fix this behavior. :)

**Comment by r10s** [comment]
great! thank you for pushing this forward!

**Comment by webratte** [comment]
This is fixed in current version 302.1

So I think it can be closed.

If I'm wrong feel free to reopen it.
